import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { loadCountry, parseCountry } from "../src/data/load-country.js";
import { advanceQuarter, createGameState, simulateQuarters } from "../src/engine/simulation.js";
import { createRng } from "../src/engine/rng.js";
import type { GameEvent } from "../src/domain/types.js";
import { restoreGameState, serializeGameState } from "../src/data/game-save.js";
import { handleWorkerRequest } from "../src/worker/simulation-worker.js";
import { advanceClock } from "../src/engine/calendar.js";

const countryPath = fileURLToPath(new URL("../data/countries/peru.json", import.meta.url));
const country = await loadCountry(countryPath);

test("country fixture contains versioned world data and structural political parameters", () => {
  assert.equal(country.id, "peru");
  assert.equal(country.dataVersion, "peru-2026-10-05-v7");
  assert.equal(country.politicalSystem.formOfGovernment, "presidential");
  assert.equal(country.politicalSystem.legislature.type, "bicameral");
  if (country.politicalSystem.legislature.type !== "bicameral") throw new Error("La ficha de Perú debe tener dos cámaras.");
  assert.equal(country.politicalSystem.legislature.lowerChamber.seats, 130);
  assert.equal(country.politicalSystem.legislature.upperChamber.seats, 60);
  assert.equal(country.electoralDistricts.length, 27);
  assert.equal(country.socialBlocks.reduce((sum, block) => sum + block.populationShare, 0), 100);
  assert.equal(country.politicalSystem.politicalDistribution.reduce((sum, group) => sum + group.sharePercent, 0), 100);
});

test("parties and legislators are generated by seed to fit the configured chambers", () => {
  const state = createGameState(country, "composicion");
  const otherState = createGameState(country, "otra-composicion");
  assert.equal(state.parties.length, country.politicalSystem.politicalDistribution.length);
  assert.equal(state.legislators.length, 190);
  assert.equal(state.legislators.filter((person) => person.chamberId === "chamber-of-deputies").length, 130);
  assert.equal(state.legislators.filter((person) => person.chamberId === "senate").length, 60);
  assert.notDeepEqual(state.parties, otherState.parties);
  assert.ok(state.legislators.every((person) => state.parties.some((party) => party.id === person.partyId)));
});

test("the same country schema and generator support a unicameral legislature", () => {
  const unicameralCountry = parseCountry(JSON.stringify({
    ...country,
    id: "fixture-unicameral",
    candidateEligibility: country.candidateEligibility.filter((rule) => rule.officeId !== "senator").map((rule) => ({ ...rule, ...(rule.chamberId ? { chamberId: "national-assembly" } : {}) })),
    partyLeadership: { ...country.partyLeadership, eligibleAfterOfficeIds: country.partyLeadership.eligibleAfterOfficeIds.filter((officeId) => officeId !== "senator") },
    ministerialAppointment: { ...country.ministerialAppointment, eligibleAfterOfficeIds: country.ministerialAppointment.eligibleAfterOfficeIds.filter((officeId) => officeId !== "senator") },
    politicalSystem: {
      ...country.politicalSystem,
      legislature: {
        type: "unicameral",
        lowerChamber: {
          ...country.politicalSystem.legislature.lowerChamber,
          seats: 101,
          districtCount: 1,
          nationalSeats: 0,
        },
      },
    },
    electoralDistricts: [{ id: "single", name: "Circunscripción única", seatsByChamber: { "chamber-of-deputies": 101 } }],
  }));
  const state = createGameState(unicameralCountry, "unicameral");
  assert.equal(state.legislators.length, 101);
  assert.ok(state.legislators.every((person) => person.chamberId === "chamber-of-deputies"));
  assert.ok(state.legislators.every((person) => person.districtId === "single"));
});

test("the same seed and country produce identical state and event history", () => {
  const firstEvents: GameEvent[] = [];
  const secondEvents: GameEvent[] = [];
  const first = simulateQuarters(country, "semilla-estable", 80, (event) => firstEvents.push(event));
  const second = simulateQuarters(country, "semilla-estable", 80, (event) => secondEvents.push(event));
  assert.deepEqual(first, second);
  assert.deepEqual(firstEvents, secondEvents);
  const fingerprint = (value: unknown): string => createHash("sha256").update(JSON.stringify(value)).digest("hex");
  assert.equal(fingerprint(first), fingerprint(second));
});

test("different seeds create distinct generated profiles and simulation histories", () => {
  const first = simulateQuarters(country, "semilla-a", 80);
  const second = simulateQuarters(country, "semilla-b", 80);
  assert.notDeepEqual(first.legislators, second.legislators);
  assert.notDeepEqual(first.eventHistory, second.eventHistory);
});

test("the engine emits annual reports through the event callback", () => {
  const events: GameEvent[] = [];
  simulateQuarters(country, "informe", 4, (event) => events.push(event));
  assert.ok(events.some((event) => event.type === "economy.annual-report"));
  assert.equal(events.filter((event) => event.type === "simulation.quarter-advanced").length, 4);
});

test("the worker message adapter uses the same deterministic engine", () => {
  const created = handleWorkerRequest({ type: "create", country, seed: "worker" });
  assert.equal(created.type, "ready");
  if (created.type !== "ready") return;
  const advanced = handleWorkerRequest({ type: "advance", country, state: created.state, quarters: 80 });
  assert.equal(advanced.type, "advanced");
  if (advanced.type !== "advanced") return;
  assert.deepEqual(advanced.state, simulateQuarters(country, "worker", 80));
  assert.ok(advanced.events.every((event) => event.explanation.length > 0));
});

test("the web worker adapter creates and advances the full world off the interface", () => {
  const created = handleWorkerRequest({ type: "world-create", countryId: "peru", seed: "worker-world" });
  assert.equal(created.type, "world-ready");
  if (created.type !== "world-ready") return;
  assert.equal(created.state.actors.length, 217);
  const advanced = handleWorkerRequest({ type: "world-advance", state: created.state, seed: "worker-world", quarters: 8 });
  assert.equal(advanced.type, "world-advanced");
  if (advanced.type !== "world-advanced") return;
  assert.equal(advanced.state.quarterIndex, 8);
  assert.equal(advanced.state.actors.length, 217);
});

test("country loader reports schema errors with a useful path", async () => {
  const directory = await mkdtemp(join(tmpdir(), "mandato-invalid-country-"));
  const path = join(directory, "bad.json");
  try {
    await writeFile(path, JSON.stringify({ schemaVersion: 1, id: "bad", name: "Inválido" }));
    await assert.rejects(loadCountry(path), /Datos de país inválidos.*startingYear/);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("saving and restoring halfway through preserves the final result", () => {
  let checkpoint = createGameState(country, "checkpoint");
  for (let index = 0; index < 40; index += 1) checkpoint = advanceQuarter(country, checkpoint).state;
  const restored = restoreGameState(serializeGameState(checkpoint), country.id);
  for (let index = 0; index < 40; index += 1) checkpoint = advanceQuarter(country, checkpoint).state;
  const uninterrupted = simulateQuarters(country, "checkpoint", 80);
  assert.deepEqual(checkpoint, uninterrupted);
  assert.equal(restored.quarterIndex, 40);
});

test("random number streams remain isolated by simulation module", () => {
  const start = createGameState(country, "aislamiento");
  const baseline = advanceQuarter(country, start).state;
  const extraSocietyDraw = createRng(start.randomStreams.society);
  extraSocietyDraw.next();
  const alteredState = {
    ...start,
    randomStreams: { ...start.randomStreams, society: extraSocietyDraw.getState() },
  };
  const afterExtraDraw = advanceQuarter(country, alteredState).state;
  assert.equal(afterExtraDraw.randomStreams.economy, baseline.randomStreams.economy);
  assert.equal(afterExtraDraw.randomStreams.politics, baseline.randomStreams.politics);
  assert.equal(afterExtraDraw.randomStreams.actors, baseline.randomStreams.actors);
});

test("calendar supports weekly and quarterly steps over year boundaries", () => {
  const start = { year: 2026, quarter: 1 as const, weekOfYear: 1 };
  const afterThirteenWeeks = advanceClock(start, { unit: "week", count: 13 });
  const afterOneQuarter = advanceClock(start, { unit: "quarter" });
  assert.deepEqual(afterThirteenWeeks, { year: 2026, quarter: 2, weekOfYear: 14 });
  assert.deepEqual(afterOneQuarter, afterThirteenWeeks);
  assert.deepEqual(advanceClock(start, { unit: "week", count: 52 }), { year: 2027, quarter: 1, weekOfYear: 1 });
});

test("legislators evolve as party discipline and approval change", () => {
  const start = createGameState(country, "legisladores-vivos");
  const advanced = advanceQuarter(country, start).state;
  assert.notDeepEqual(advanced.legislators, start.legislators);
  assert.ok(advanced.legislators.every((person) => person.loyalty >= 0 && person.loyalty <= 100));
});
