import { readFile, writeFile } from "node:fs/promises";
const escape = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll("\"", "&quot;");
const packages = ["react", "react-dom", "scheduler", "zod", "lucide-react"];
let notices = "MANDATO — Avisos de dependencias distribuidas\n\n";
for (const name of packages) {
  const pkg = JSON.parse(await readFile(`node_modules/${name}/package.json`, "utf8"));
  notices += `${name} ${pkg.version} — ${pkg.license}\n${await readFile(`node_modules/${name}/LICENSE`, "utf8")}\n\n`;
}
for (const font of ["source-serif", "source-sans"]) notices += `${font} — OFL-1.1\n${await readFile(`public/assets/fonts/${font}-LICENSE.md`, "utf8")}\n\n`;
await writeFile("dist/THIRD-PARTY-NOTICES.txt", notices);
const manifest = JSON.parse(await readFile("public/data/countries/index.json", "utf8"));
const memberships = JSON.parse(await readFile("src/data/world-memberships.json", "utf8"));
const organizationLabels = { un: "ONU", eu: "Unión Europea", nato: "OTAN", mercosur: "MERCOSUR", asean: "ASEAN", au: "Unión Africana", wto: "OMC", imf: "FMI", "world-bank": "Banco Mundial: IBRD" };
let sources = `<h2>Membresías de organismos</h2><p>Consulta ${escape(memberships.snapshotDate)}. Las listas oficiales se separan de las condiciones, préstamos y disputas ficticios del juego.</p><ul>${Object.entries(memberships.rosters).map(([id, roster]) => `<li><a href="${escape(roster.sourceUrl)}" target="_blank" rel="noreferrer">${escape(organizationLabels[id] ?? id)}</a>: ${roster.officialMemberCount} miembros oficiales; ${roster.representedActorCount} actores representados.${roster.unrepresentedMembers.length ? ` Sin actor independiente: ${roster.unrepresentedMembers.map((member) => escape(member.name)).join(", ")}.` : ""}${roster.scopeNote ? ` ${escape(roster.scopeNote)}` : ""}</li>`).join("")}</ul>`;
for (const entry of manifest.countries) {
  const country = JSON.parse(await readFile(`public/data/countries/${entry.file}`, "utf8"));
  sources += `<h2>${escape(country.name)}</h2><p>Versión ${escape(country.dataVersion)}. ${country.experimental ? "Perfil experimental: las agregaciones institucionales y parámetros de juego no son observaciones." : "Los parámetros de juego se distinguen de las observaciones citadas."}</p><ul>${country.dataSources.map((source) => `<li><a href="${escape(source.url)}" target="_blank" rel="noreferrer">${escape(source.name)}</a> · ${escape(source.indicator)} · período ${source.year} · consulta ${source.accessedOn}</li>`).join("")}</ul>`;
}
await writeFile("dist/credits.html", `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Créditos y fuentes · MANDATO</title><style>body{max-width:900px;margin:auto;padding:24px;background:#101815;color:#e9e9df;font:1rem/1.7 system-ui}a{color:#d2e3a3}li{margin:10px 0}</style><a href="/">← Volver a MANDATO</a><h1>Créditos y fuentes</h1><p>Ficción política y sátira. Personajes, partidos y reglas de simulación se generan localmente; no se importan dirigentes ni resultados actuales. Los escenarios generados usan una plantilla institucional ficticia común.</p><p>Datos mundiales: World Bank, World Development Indicators, instantánea 6 de octubre de 2026. Extracción y redondeo por MANDATO; relaciones comerciales derivadas y ausencias marcadas. <a href="https://datacatalog.worldbank.org/public-licenses">Términos del Banco Mundial</a> (CC BY 4.0 como licencia por defecto; algunos indicadores de terceros pueden tener condiciones adicionales). Mapa: <a href="https://www.naturalearthdata.com/about/terms-of-use/">Natural Earth, dominio público</a>, Admin 0 1:110m; geometrías simplificadas. Roster ONU y clasificación de disuasión: referencias ONU y FAS registradas en el snapshot. No representan un aval al juego.</p><p>Dirección de arte: realismo político cinematográfico. Despacho inicial, seis asesores y 24 personajes generados con IA en ChatGPT; originales aportados por el usuario e integrados el 7 de octubre de 2026. Se añadieron 16 personajes, 24 ilustraciones de acontecimientos, un hemiciclo, una sede de campaña y un despacho nacional con imagegen: 40 rostros y seis asesores en total. <a href="https://openai.com/policies/terms-of-use/">Términos de OpenAI</a>. Los retratos raster representan personas ficticias; los originales se conservan y los recortes se registran en el manifiesto de assets. Los fondos, texturas y sonidos sintetizados restantes son originales de MANDATO. Lluvia, música ambiental de cámara y señales de interacción se sintetizan localmente; el audio está desactivado inicialmente y requiere interacción para activarse. Tipografía Source Serif 4 y Source Sans 3 de Adobe (OFL-1.1), alojadas localmente. Iconos Lucide (ISC y MIT para derivados de Feather).</p><p><a href="/THIRD-PARTY-NOTICES.txt">Avisos de dependencias, iconos y fuentes</a>. La revisión de términos específicos de fuentes institucionales e indicadores de terceros y del alojamiento sigue pendiente antes de un lanzamiento público.</p>${sources}</html>`);
