import { worldName } from './world-names.js';
import { useEffect, useRef, useState } from 'react';
import { Compass, Minus, Plus } from 'lucide-react';
import type { AggregateForce } from '../domain/geopolitics-types.js';
import { Button } from './ui/UI.js';

type Position = [number, number, ...number[]];
type Geometry = { type: 'Polygon' | 'MultiPolygon'; coordinates: Position[][] | Position[][][] };
type Feature = { id: string; name: string; continent: string; geometry: Geometry };
type MapData = { snapshotDate: string; features: Feature[] };
function geometryPath(geometry: Geometry): string { const polygons = geometry.type === 'Polygon' ? [geometry.coordinates as Position[][]] : geometry.coordinates as Position[][][]; return polygons.flatMap((polygon) => polygon.map((ring) => ring.map(([longitude,latitude],index) => `${index ? 'L' : 'M'}${((longitude+180)/360*960).toFixed(1)},${((90-latitude)/180*480).toFixed(1)}`).join(' ')+'Z')).join(' '); }
const forceLabels = { land:'Ejército',naval:'Flota',air:'Fuerza aérea' };

export function WorldMap({ selectedId, onSelect, colorFor, forces = [] }: { selectedId: string; onSelect: (id: string) => void; colorFor: (id: string) => string; forces?: readonly AggregateForce[] }) {
  const [data,setData] = useState<MapData | null>(null); const [error,setError] = useState(false); const [zoom,setZoom] = useState(1); const [pan,setPan] = useState({x:0,y:0});
  const drag = useRef<{x:number;y:number;px:number;py:number} | null>(null); const moved = useRef(false);
  useEffect(() => { let active = true; void fetch('/data/world/world-map.json').then((response) => { if (!response.ok) throw new Error('Mapa no disponible'); return response.json() as Promise<MapData>; }).then((map) => { if (active) setData(map); }).catch(() => { if (active) setError(true); }); return () => { active=false; }; },[]);
  if (error) return <p role="status">No se pudo cargar el mapa. Usa el catálogo de países.</p>;
  if (!data) return <div className="world-map-loading" role="status">Desplegando el mapa…</div>;
  const changeZoom = (value: number) => { const next = Math.max(1,Math.min(5,value)); setZoom(next); if (next === 1) setPan({x:0,y:0}); else setPan((previous) => ({ x: 480-(480-previous.x)*next/zoom, y:240-(240-previous.y)*next/zoom })); };
  return <div className="political-map"><svg className="world-map" viewBox="0 0 960 480" role="group" aria-label="Mapa político del mundo. Elige un país o usa el catálogo." onPointerDown={(event) => { if (event.button !== 0) return; moved.current=false; drag.current={x:event.clientX,y:event.clientY,px:pan.x,py:pan.y}; }} onPointerMove={(event) => { if (!drag.current || zoom===1) return; const rect=event.currentTarget.getBoundingClientRect(); const dx=(event.clientX-drag.current.x)*960/rect.width; const dy=(event.clientY-drag.current.y)*480/rect.height; if (Math.abs(dx)+Math.abs(dy)>5) { moved.current=true; event.currentTarget.setPointerCapture(event.pointerId); setPan({x:drag.current.px+dx,y:drag.current.py+dy}); } }} onPointerUp={(event) => { drag.current=null; if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); }} onPointerCancel={() => { drag.current=null; }}>
    <defs><pattern id="map-grid" width="80" height="80" patternUnits="userSpaceOnUse"><path d="M80 0H0V80" fill="none" stroke="#BEB99D" strokeWidth=".5" opacity=".12"/></pattern><pattern id="map-grain" width="7" height="9" patternUnits="userSpaceOnUse"><path d="M1 2h1M4 7h1" stroke="#F4EAD3" opacity=".1"/></pattern></defs><rect width="960" height="480" fill="#101C18"/><rect width="960" height="480" fill="url(#map-grid)"/>
    <g transform={`translate(${pan.x},${pan.y}) scale(${zoom})`}>{data.features.map((feature) => { const id=feature.id.toLowerCase(); const name=worldName(id, feature.name); return <path key={feature.id} d={geometryPath(feature.geometry)} fill={id===selectedId.toLowerCase() ? '#d4b47b' : colorFor(id)} stroke="#101C18" strokeWidth={.7/zoom} tabIndex={0} role="button" aria-label={name} aria-pressed={id===selectedId.toLowerCase()} onClick={() => { if (!moved.current) onSelect(id); }} onKeyDown={(event) => { if (event.key==='Enter' || event.key===' ') { event.preventDefault(); onSelect(id); } }}><title>{name}</title></path>; })}
    {forces.map((force,index) => { const feature=data.features.find((item) => item.id.toLowerCase()===force.locationId); if (!feature) return null; const polygon=feature.geometry.type==='Polygon' ? feature.geometry.coordinates as Position[][] : (feature.geometry.coordinates as Position[][][])[0]!; const ring=polygon[0]!; const longitude=ring.reduce((sum,point) => sum+point[0],0)/ring.length; const latitude=ring.reduce((sum,point) => sum+point[1],0)/ring.length; const x=(longitude+180)/360*960+(index%3-1)*5; const y=(90-latitude)/180*480; return <g key={`${force.ownerId}-${index}`} transform={`translate(${x},${y})`}><path d="M0 10V-8l12 3-12 3" fill="#D2AF61" stroke="#0B100E" strokeWidth="1"/><title>{forceLabels[force.kind as keyof typeof forceLabels] ?? 'Fuerzas'} · {force.ownerId} · logística {force.logistics.toFixed(0)}</title></g>; })}</g><rect width="960" height="480" fill="url(#map-grain)" pointerEvents="none"/>
  </svg><div className="map-zoom" aria-label="Controles del mapa"><Button variant="secondary" aria-label="Acercar mapa" disabled={zoom===5} onClick={() => changeZoom(zoom+.5)}><Plus size={18}/></Button><Button variant="secondary" aria-label="Alejar mapa" disabled={zoom===1} onClick={() => changeZoom(zoom-.5)}><Minus size={18}/></Button><Button variant="secondary" aria-label="Restablecer mapa" onClick={() => { setZoom(1);setPan({x:0,y:0}); }}><Compass size={18}/></Button></div><span className="map-compass" aria-hidden="true">N<br/>✦</span><span className="map-instruction">Elige un país · acerca para explorar</span></div>;
}
