import { useState } from 'react';
import { Button, Card, Chip, Drawer, Figure, Modal, Notice, Portrait, Selector, Switch, Tabs, Tooltip } from './ui/UI.js';
import { DeskScene } from './DeskScene.js';
import type { CareerGameState } from '../domain/career-types.js';
import type { CountryDefinition } from '../domain/types.js';

export function UIKit({ state, country }: { state: CareerGameState; country: CountryDefinition }) {
  const [choice,setChoice] = useState('dialogue'); const [reduced,setReduced] = useState(false); const [tab,setTab] = useState('components'); const [modal,setModal] = useState<'modal' | 'drawer' | null>(null); const [value,setValue] = useState(35); const [mood,setMood] = useState<'day' | 'night' | 'crisis'>('day');
  return <main className="ui-kit"><header><span className="eyebrow">MANDATO · TALLER DE INTERFAZ</span><h1>El lenguaje del juego</h1><a href="/">Volver al juego</a></header><Tabs value={tab} onChange={setTab} options={[{id:'components',label:'Componentes'},{id:'portraits',label:'Retratos'},{id:'office',label:'Atmósferas'}]}/>{tab === 'portraits' ? <div className="portrait-sheet">{Array.from({length:24},(_,index) => <Card key={index}><Portrait identity={`politician-${index}`} name={`Personaje ${index+1}`} age={25+index*2}/><span>Personaje {index+1}</span></Card>)}</div> : tab === 'office' ? <><Tabs value={mood} onChange={setMood} options={[{id:'day',label:'Día'},{id:'night',label:'Noche'},{id:'crisis',label:'Crisis'}]}/><DeskScene state={state} country={country} mood={mood} navigate={() => {}}/></> : <div className="kit-grid"><Card><h2>Acciones</h2><Button>Decidir</Button><Button variant="secondary">Negociar</Button><Button disabled>Sin recursos</Button><Tooltip text="Cada acción deja una memoria">Ver contexto</Tooltip></Card><Card><h2>Costos y cambios</h2><div className="chip-row"><Chip tone="agency">+12 confianza</Chip><Chip>−5 capital</Chip><Chip tone="crisis">Crisis</Chip><Chip tone="gold">Mandato ganado</Chip></div><Figure value={value}/><Button variant="quiet" onClick={() => setValue(value+3)}>Sumar 3</Button></Card><Card><h2>Opciones</h2><Selector value={choice} aria-label="Respuesta" onChange={(event) => setChoice(event.target.value)}><option value="dialogue">Abrir el diálogo</option><option value="pressure">Presionar públicamente</option><option value="unavailable" disabled>Acuerdo no disponible</option></Selector><Switch label="Reducir movimiento" checked={reduced} onChange={setReduced}/><Notice>La decisión queda en tu diario.</Notice></Card><Card><h2>Personas y expedientes</h2><Portrait identity="advisor-economy" name="Asesora de economía"/><Button variant="secondary" onClick={() => setModal('drawer')}>Abrir expediente</Button><Button variant="quiet" onClick={() => setModal('modal')}>Abrir diálogo</Button></Card></div>}{modal && (modal === 'drawer' ? <Drawer title="El expediente" onClose={() => setModal(null)}><p>El detalle aparece cuando lo necesitas.</p><Selector aria-label="Respuesta en expediente" value={choice} onChange={(event) => setChoice(event.target.value)}><option value="dialogue">Abrir el diálogo</option><option value="pressure">Presionar públicamente</option></Selector><Button onClick={() => setModal(null)}>Cerrar</Button></Drawer> : <Modal title="Un momento para decidir" onClose={() => setModal(null)}><p>El foco permanece dentro. Escape cierra y devuelve el foco.</p><Button onClick={() => setModal(null)}>Continuar</Button></Modal>)}</main>;
}
